language: node_js
node_js:
- '4.1'
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- npm install grunt-cli -g
- npm install protractor -g
- webdriver-manager update
- webdriver-manager start 2>&1 &
- sleep 5