language: node_js
node_js:
- '4.1'
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- npm install grunt-cli -g
addons:
  sauce_connect:
      username: "NormanColoma"
      access_key:
        secure: "923e35c3-a5a6-4518-b002-21b52dd559f1"