language: node_js
node_js:
- '4.1'
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- npm install grunt-cli -g
deploy:
  provider: heroku
  app: justsportapp
  api_key:
    secure: "31dcaa24-8994-4def-a702-0e4a6e2a9915"
