language: node_js
node_js:
- '4.1'
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- npm install grunt-cli -g
addons:
  sauce_connect:
      username: "NormanColoma"
      access_key:
        secure: "RyGAdxlXqxE9G926uuTWvsunX0KtYoBUXCU3vVDTqsG4IWwtsBac5GuAVeTvRkBgdLudrRUQC+HPcsTRNiHjGog/AD+SJNnz970HICRtSiZC/sjM+Msc7JqU855UTC7n1RoBHdPOu0cHUh2KFeUjBThxGHPKb6msXcGkcZ7Ysv6YlNbbl38vFcfxigVdSsL5HLDBPgckVfNRqtcQontngZ4WbNmfgKNTLd6fjKbdBwbgeFIEdPAVRHPmv5Exl20oVGwCU84rfPK89Ci0UkweXIBT8QnB64jWsmV1qk35IEa39TN/cGpUmWChk66c5wknUOoMai9Ze3g0ic64yjLRN1pmUauOTvehQISQTUNXmGeE+E7A6XT1pHCmolUmLScrFa/XZN2wh8TWbIgWrwOk36HTAveu/wORG0VjGl0742I94u6JmbT/wsqLPzW4A+Fr6/0GXu35VLbhdPDrXNbRv8RRy+1lpuY7tKk0wVeY1q/FaeRRcQfZEzEXyP/XLf1h80kFceCcs+8wHc+g23KG4WPMvl4J4oLO8FJfPOb2EoW95xDsOlxOYOLP8CdcvBAuFHNjj8qR0cLLYjyRk+mp16OcQE78U/a1bomShsiZS4fD00p2gMDvtZUOiKxlqsW+NXWw1wTQUBDJ206qSXBzZVNSNDwFI5/7sSpLfyWLVww="
