language: node_js
sudo: true
node_js:
  - '4.1'
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - webdriver-manager update
  - webdriver-manager start
before_script:
  - npm install grunt-cli -g
