language: node_js
node_js:
- '4.1'
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- npm install grunt-cli -g
addons:
  sauce_connect: true
env:
  global:
  - secure: XdsmQ+zShUZLkH3oGkQUOns9GupGiINy64b0hWGy3dl4nTGz/GxoenwZPOXYCAotGtYpXoHneGf8nshNNXyKDno+yKVuIZfBZ+u5EdJHKtDga0YbEJj1ALWoC1hKmtlzJzJWvvlQzxHXj5M75K+tpB4VrUbOXV19ZtYRDWsQuSf6dUVITQjbmCwSCQ+TDaX0EGW2sdAW5/DqOI8AIOGVP0z1x5jQMTOHrJpw/N0cZInPS+RObOz80AcHD8AA4lXsHfv2ERgPPcl9ryzgafKy3RMuk4y9zvTsyRomHuG2MkKRjM6WzWaLJkpEYgySZbxnSENiriBGNKTKyWNZMKdAflVLXBKBxZ6Wm/HNlUDD5/b0JeFBt8V2H1s2oLzbamxj+Z2fMLfHPRvgdNXemU9Am/UrD9WCqLQK9ZFtz/D+/l0Z7RvLFu+aHR+1tjTF1Ll69gslRoyTTSa2HtCRypdljGyuSM2LCUX/0+dTTv8xeEd6xrZ/5Aq1ZeQzJSBSZzuG45YZOSTTIQc54L+xb5rWChVWDBQtktTLBnCXWlEriiGnQKzNHh6p8Wjtg9kAoTBaXOm1kaUW9JSNQE5iCv/jiA/lzRlQpN6+5q7klxETF3crVo35btCtJ3VGOLMO0NPrIep1mc8eptePS8kaIJaJmPL3xFJd4NwERWabGHhv4Gg=
  - secure: YML13u2JKhHNJfK10E4cR80ZY0j4e5w8wr8y6rUT84YSJ6XMPemfM0kJ56I1TpRmbBdkBwUj+UcCP67JftCwByoMrFjkgRBa89dzzOI0RJ+X+O6iaLiEwWB2pA27AXiXo4DcpfT6aybxoaPRKXW0x0lqXKlMosAXqcB8/IEg685K/NtXbQ64/tcyI1XtMIc6BSMOOUv4Vlx1o5H1dGND/QLqq3b7xv8I2nhZfGbot2KlBxsSU5HQWTSheek0Z0GCGxLVkiJWQvvkHxMcslyypzWgsikeKZpmPZ0jGgbC7ZMAJsVzNpvMpPvQ1FSR9ZI3ycTduZIGhvzDPWJE4CGPAJft546WJ36UucD/8ptY+vvOLIJcgEZGszpChHsUKX16s67oYgEN69ydTfiFYeN94Zn3HEN/ODqrEQMB0HW6mb27hj/Z6eJKZLgaKVXfh9930yieeLDbpdV73tIuDBW0iAtromZNG+0KxQkAZ2Kp3q8BRcj3c5FNtGdFubuVFEhItDLQURnME82F/0n7MSQQnXEqoNWQgK4QCrPWhJ+wNHpsLqdpSYZF4lfBrFUX/Yjtu/ZQpUueIXLmbQ2vivNFm/69yJj5vsTxzGpArsuXbWpUbCYoquCzhuspDeJINobqw2PKpXAtKgphy5NZcflZ05+iq6m7H9iNTL5Gwhp8vuc=
